version: "3.7"
services:
  app:
    build:
      args:
        user: abdalla
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: wishlist
    container_name: wishlist-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - wishlist-network

  db:
    image: mysql:8.0
    container_name: wishlist-db
    restart: unless-stopped
    ports:
      - 3366:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - wishlist-network

  nginx:
    image: nginx:alpine
    container_name: wishlist-nginx
    restart: unless-stopped
    ports:
      - 3000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - wishlist-network

  phpmyadmin:
    depends_on:
     - db
    image: phpmyadmin/phpmyadmin
    container_name: 'wishlist-PHPMYADMIN'
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - UPLOAD_LIMIT=1024M
    ports:
      - 81:80
    links:
      - db    
    networks:
      - wishlist-network

networks:
  wishlist-network:
    driver: bridge